# Generated by Django 2.2.25 on 2022-01-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutgroup',
            name='workout_type',
            field=models.PositiveIntegerField(choices=[(0, 'Series'), (1, 'Challange'), (2, 'Testing')], default=0, verbose_name='Workout Type'),
            preserve_default=False,
        ),
    ]
