# Generated by Django 2.2.25 on 2022-01-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_auto_20220102_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutgroup',
            name='workout_type',
            field=models.PositiveIntegerField(choices=[(0, 'Series'), (1, 'Challange'), (2, 'Standalone')], verbose_name='Workout Type'),
        ),
    ]
