# Generated by Django 2.2.25 on 2022-06-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_auto_20220102_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandaloneWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='workout Name')),
                ('video_tutorial', models.FileField(blank=True, null=True, upload_to='workout_tutorials')),
                ('need_subscription', models.BooleanField(default=False)),
            ],
        ),
    ]
