# Generated by Django 2.2.25 on 2022-06-24 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_standaloneworkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='workout Name')),
                ('video_tutorial', models.FileField(blank=True, null=True, upload_to='workout_tutorials')),
                ('need_subscription', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StandaloneWorkoutSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetition_number', models.PositiveIntegerField(blank=True, null=True)),
                ('disk_position', models.CharField(blank=True, max_length=255, null=True)),
                ('series_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.SeriesWorkout')),
                ('standalone_workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.StandaloneWorkout')),
            ],
        ),
        migrations.AddField(
            model_name='seriesworkout',
            name='standalone_workouts',
            field=models.ManyToManyField(through='workout.StandaloneWorkoutSetup', to='workout.StandaloneWorkout'),
        ),
    ]
