# Generated by Django 2.2.25 on 2022-06-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_auto_20220624_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='burn_calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='workout_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='workout_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
