# Generated by Django 2.2.25 on 2022-06-24 23:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout', '0009_auto_20220624_2307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkoutLog',
            new_name='WorkoutHistory',
        ),
    ]
