# Generated by Django 2.2.25 on 2021-12-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
